### ISSUE TITLE
Allow VFS options that don't use the same vfs_object name

### ISSUE THREAD

**Issue by andrewradke** [vladgh/ansible-collection-vladgh-samba#101]
The VFS shadow_copy2 uses `shadow:option_name` instead of `shadow_copy2 :option_name`

Currently the smb.conf.j2 template doesn't allow for this.
I'd like to propose checking for a : in the option name. If it includes one then treat it as complete and leave out the object name. Otherwise operate as it currently does.

```
 {% for opt in obj.options %}
+{% if ':' in opt.name %}
+  {{ opt.name }} = {{ opt.value }}
+{% else %}
   {{ obj.name }}:{{ opt.name }} = {{ opt.value }}
+{% endif %}
 {% endfor %}
```

The following YAML would then produce the share definition below it without affecting existing configs.
```
        samba_shares:
          - name: "ShareName"
            vfs_objects:
              - name: shadow_copy2
                options:
                  - name: shadow:snapdir
                    value: /data/shares/.shadow_snapshots
                  - name: shadow:sort
                    value: desc
                  - name: shadow:snapsharepath
                    value: RedirectedFolders
```

```
[ShareName]
  vfs objects = shadow_copy2
  shadow:snapdir = /data/shares/.shadow_snapshots
  shadow:sort = desc
  shadow:snapsharepath = RedirectedFolders
```

If you are happy with this I can create another pull request.
