### ISSUE TITLE
VFS options should also be accepted on the [Global] level

### ISSUE THREAD

**Issue by RlndVt** [vladgh/ansible-collection-vladgh-samba#133]
e.g. the follwoing should also be valid syntax:
```
    - name: Include Samba Server role
      ansible.builtin.include_role:
        name: vladgh.samba.server
      vars:
        # [GLOBAL]
        # [...]
        vfs_objects:
          - name: fruit
            options:
              - name: [...]
                value: 'Yes'
          - name: streams_xattr
        samba_shares:
          - name: 'Name'
            vfs_objects:
              - name: fruit
                options:
                  - name: [...]
                    value: 'Yes'
              - name: streams_xattr
```

Current workaround is using `samba_global_include`.
