### ISSUE TITLE
Error 'ansible_distribution' is undefined

### ISSUE THREAD

**Issue by Apollo3zehn** [vladgh/ansible-collection-vladgh-samba#202]
I get the following error when trying to import the role:

```
FAILED! => {"msg": "The task includes an option with an undefined variable.. {'files': ['os_{{ ansible_distribution }}.yml', 'os_{{ ansible_os_family }}.yml'], 'paths': ['vars']}: 'ansible_distribution' is undefined\n\nThe error appears to be in '/home/vincent/.ansible/collections/ansible_collections/vladgh/samba/roles/server/tasks/main.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Include OS specific variables\n  ^ here\n"}
```

The reason is that in my `ansible.cfg` I have `INJECT_FACTS_AS_VARS=false` for security reasons. This means that there are no `ansible_`-prefixed variables. To avoid these kind issues, it is safer to use the original variable `ansible_facts.distribution` instead (example, this applies to all Ansible variables used in this role). My workaround for now is to define the missing variables:

```yaml
    - name: Import role vladgh.samba.server
      become: true
      ansible.builtin.import_role:
        name: vladgh.samba.server
      vars:
        ansible_distribution: "{{ ansible_facts.distribution }}"
        ansible_os_family: "{{ ansible_facts.os_family }}"
        ...
```
