### ISSUE TITLE
Samba share is not configured according to playbook

### ISSUE THREAD

**Issue by Tronde** [vladgh/ansible-collection-vladgh-samba#62]
The following playbook is used to:

1. Create a system group `alice`
2. Create a system user `alice`
3. Creates `/tmp/testdir1`, sets owner and group to `alice:alice` and mode '0770'
4. Includes role to configure the share

## Playbook to reproduce

```
---
- hosts: foo.example.com
  debugger: on_failed
  vars_files:
    - files/my.vars
  vars:
    system_user: alice
    system_group: alice
    user_pass: foo123!

  tasks:
    - name: Create system group {{ system_group }}
      ansible.builtin.group:
        name: "{{ system_group }}"
        state: present
        system: true
        
    - name: Create system user {{ system_user }}
      ansible.builtin.user:
        name: "{{ system_user }}"
        shell: /usr/sbin/nologin
        group: "{{ system_group }}"
        state: present
        system: true

    - name: Allow write access for group {{ system_group }}
      ansible.builtin.file:
        path: /tmp/testdir1
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_group }}"
        mode: '0770'

    - name: Include role vladgh.samba.server
      include_role:
        name: vladgh.samba.server
      vars:
        samba_users:
          - name: "{{ system_user }}"
            password: "{{ user_pass }}"
        samba_shares:
          - name: testdir1
            path: /tmp/testdir1
            read_only: no
            guest_ok: no
            browseable: yes
            owner: "{{ system_user }}"
            group: "{{ system_user }}"
```

## Actual results

```
$ ls -ld /tmp/testdir
drwxrwxr-x 2 alice alice 4096 17. Apr 13:40 /tmp/testdir1

$ testparm
Load smb config files from /etc/samba/smb.conf
Loaded services file OK.
Weak crypto is allowed
Server role: ROLE_STANDALONE

Press enter to see a dump of your service definitions

# Global parameters
[global]
        disable spoolss = Yes
        domain master = Yes
        load printers = No
        logging = syslog
        preferred master = Yes
        printcap name = /dev/null
        security = USER
        server string = Fileserver %m
        wins support = Yes
        idmap config * : backend = tdb
        printing = bsd


[testdir1]
        create mask = 0664
        directory mask = 0775
        force create mode = 0664
        force directory mode = 0775
        force group = alice
        path = /tmp/testdir1
```

The share `testdir1`is not writeable for the user `alice`.

## Expected result

```
$ ls -ld /tmp/testdir
drwxrwxr-x 2 alice alice 4096 17. Apr 13:40 /tmp/testdir1

$ testparm
Load smb config files from /etc/samba/smb.conf
Loaded services file OK.
Weak crypto is allowed
Server role: ROLE_STANDALONE

Press enter to see a dump of your service definitions

# Global parameters
[global]
        disable spoolss = Yes
        domain master = Yes
        load printers = No
        logging = syslog
        preferred master = Yes
        printcap name = /dev/null
        security = USER
        server string = Fileserver %m
        wins support = Yes
        idmap config * : backend = tdb
        printing = bsd


[testdir1]
        create mask = 0664
        directory mask = 0775
        force create mode = 0664
        force directory mode = 0775
        force group = alice
        path = /tmp/testdir1
        read only = No
```

The share `testdir1`is writeable for the user `alice`.

## What's causing this?

The playbook didn't set the parameter `read only = No` for the share definition. After adding this parameter manually and reloading config (`systemctl reload smbd`) the share is writable as expected.

## Version information

```
$ ansible-galaxy collection list

# /home/tronde/.ansible/collections/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.5.2  
vladgh.samba  3.1.1

$ ansible-playbook --version
ansible-playbook [core 2.13.3]
  config file = /home/tronde/.ansible.cfg
  configured module search path = ['/home/tronde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/tronde/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

Ansible is running on a RHEL 9.1 host. Target host is Debian 11.6.
