### ISSUE TITLE
Making 'server' clear that it is a role instead of module in README.md

### ISSUE THREAD

**Issue by Sheshydev** [vladgh/ansible-collection-vladgh-samba#90]
Hi there, 

I was wondering if it was possible to add something to make the README file more accessible towards Ansible beginners like myself.

Initially, I thought that `vladgh.samba.server` would be written like a module like the following below:

```yml
- name: setup new samba share user
    vladgh.samba.server:
      samba_users:
        ...
      samba_shares:
        ...
```

This would lead to the error

```
ERROR! couldn't resolve module/action 'server'. This often indicates a misspelling, missing collection, or incorrect module path.
```

after a bit of digging, I then learnt what a role was and also the fact that `server` was a role, not a module, which to a beginner like myself is something I easily overlooked/forgot when reading the Ansible docs. The correct way was to write out:

```yaml
- name: setup new samba share user
    include_role:
      name: vladgh.samba.server
    vars:
      samba_users:
        ...
      samba_shares:
        ...
```

The current version of the README does not have a similar code structure to the above snippet.

could I perhaps contribute to the README file to make this clearer?
